apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-jqbq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-jqbq
    app.kubernetes.io/part-of: test-rhtap-61-app
  name: devfile-sample-code-with-quarkus-jqbq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-jqbq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-jqbq
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-61-tenant/test-rhtap-61-app/devfile-sample-code-with-quarkus-jqbq@sha256:9cd2df349779fac212de0acde5c3d5683f77c431e2e59f725b4c44d1caea68b5
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
